#!/bin/sh
# Set Zipit Z2 CPU Speed
# Use: cpu <level>
# level can be: max, high, med, low, min
# for max to work you must add the kernel boot paramenter:
# cpufreq-pxa2xx.pxa27x_maxfreq=520
#
# Copyright (c) 2012 Joseph Honold <mozzwald@gmail.com>
# Copyright (c) 2013 Mark Majeres <mark@engine12.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# make sure we are root
if [ "$(id -u)" != "0" ]; then
echo "This script must be run as root" 1>&2
    exit 1
fi

case $1 in
	"max")
		speed=520000;;
	"high")
		speed=416000;;
	"med")
		speed=312000;;
	"low")
		speed=208000;;
	"min")
		speed=104000;;

	"--")
		speed=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
		speed=$((speed-104000));;

	"++")
		speed=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
		speed=$((speed+104000));;

	*)
		exit 1;;
esac


echo "$speed" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed

speed=`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq`
echo `printf "CPU Speed set to %.3s MHz" $speed`






