#!/bin/sh
# Toggle USB mode (or specify with command line switch)

mode=`cat /sys/devices/platform/z2-usb-switch/usb_mode`
if [ -z "$1" ]; then
	# We toggle
	if [ "$mode" == "device" ]; then
		echo "host" > /sys/devices/platform/z2-usb-switch/usb_mode
		echo "Switched to USB Host mode"
	else
		echo "device" > /sys/devices/platform/z2-usb-switch/usb_mode
		echo "Switched to USB Device mode"
	fi
else
	# We set based on switch
	if [ "$1" == "d" ]; then
		echo "device" > /sys/devices/platform/z2-usb-switch/usb_mode
		echo "Switched to USB Device mode"
	elif [ "$1" == "h" ]; then
		echo "host" > /sys/devices/platform/z2-usb-switch/usb_mode
		echo "Switched to USB Host mode"
	else
		echo "Usage: usbtog <mode>"
		echo "<mode> d for device, h for host, or none to toggle"
		echo "Current mode: $mode"
	fi
fi
